//-------------------------------------------------------------
//    Copyright 2011 Synopsys, Inc.
//    All Rights Reserved Worldwide
//
// SYNOPSYS CONFIDENTIAL - This is an unpublished, proprietary work of
// Synopsys, Inc., and is fully protected under copyright and trade
// secret laws. You may not view, use, disclose, copy, or distribute this
// file or any information contained herein except pursuant to a valid
// written license from Synopsys.
//
//-------------------------------------------------------------

//
// The content of this file is normally generated by ralgen
//


#ifndef __SYS__H__
#define __SYS__H__


#include <stdlib.h>

#include "snps_reg_rw_api.h"
#include "comp1.h"
#include "comp2.h"

class sys_t : public snps_reg::regmodel
{

public:
    comp1_t Comp1a;
    comp1_t Comp1b;
    comp2_t Comp2;
        
    sys_t(const char* const name,
          size_t baseAddr,
          snps_reg::regmodel *parent = 0)
        : regmodel(parent, name, baseAddr),
        Comp1a("Comp1a", baseAddr+0x1a0000, this),
        Comp1b("Comp1b", baseAddr+0x1b0000, this),
        Comp2("Comp2", baseAddr+0x20000, this)
        {}

    sys_t(int ctxt)
        : regmodel(ctxt),
        Comp1a("Comp1a", 0, this),
        Comp1b("Comp1b", 0, this),
        Comp2("Comp2", 0, this)
        {}
};

#endif
